---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - brew-php-switcher
  - composer
  - cowsay
  - dnsmasq
  - doxygen
  - exolnet/deprecated/php@5.6
  - exolnet/deprecated/php@7.0
  - gettext
  - ffmpeg
  - gifsicle
  - git
  - git-flow
  - git-lfs
  - go
  - gource
  - gpg
  - graphicsmagick
  - hashcat
  - httpd
  - httpie
  - hub
  - imagemagick
  - iperf
  - jpeg
  - jpegoptim
  - libevent
  - lynx
  - mariadb
  - mcrypt
  - midnight-commander
  - nano
  - ncdu
  - ngrep
  - nmap
  - node
  - nvm
  - openssl
  - optipng
  - pandoc
  - pbzip2
  - php
  - php@7.1
  - php@7.2
  - pngcrush
  - pv
  - qcachegrind
  - readline
  - rename
  - rsync
  - sqlite
  - ssh-copy-id
  - the_silver_searcher
  - tesseract
  - tree
  - watch
  - wget
  - wget
  - wrk
  - z
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search


homebrew_taps:
  - exolnet/deprecated
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-creative-cloud
  - alfred
  - atom
  - ccleaner
  - dash3
  - dictionaries
  - docker
  - dropbox
  - fantastical
  - firefox
  - fluor
  - google-chrome
  - handbrake
  - install-disk-creator
  - istat-menus
  - licecap
  - limechat
  - logmein-hamachi
  - mathpix-snipping-tool
  - mia-for-gmail
  - mplayerx
  - pullover
  - rescuetime
  - sequel-pro
  - sourcetree
  - spectacle
  - sublime-text
  - the-unarchiver
  - transmission
  - transmit
  - tripmode
  - typora
  - vagrant
  - visual-studio-code
  - vlc
  - vmware-fusion
  - whatsapp
  - wkhtmltopdf
  - yacreader
  - yed

homebrew_cask_uninstalled_apps:
  - chromedriver
  - macvim
  - skitch
  - slack

homebrew_upgrade_all_packages: no

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 425264550, name: "Blackmagic Disk Speed Test (3.0)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: 
  - name: drush/drush
  - name: hirak/prestissimo
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: 
  - name: alfred-fkill
  - name: castnow
  - name: fkill-cli
  - name: gify
  - name: git-pull-all
  - name: pm2
  - name: tldr
  - name: vtop
  - name: yarn
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: 
  - name: mkdocs
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
