---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - composer
  - cowsay
  - dnsmasq
  - doxygen
  - gettext
  - gifsicle
  - git
  - git-flow
  - git-lfs
  - go
  - gpg
  - httpd
  - httpie
  - hub
  - iperf
  - libevent
  - lynx
  - mariadb
  - mcrypt
  - midnight-commander
  - nano
  - ncdu
  - nmap
  - node
  - nvm
  - openssl
  - pandoc
  - php
  - pv
  - readline
  - rename
  - sqlite
  - ssh-copy-id
  - tesseract
  - wget
  - wrk
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search



homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - dash3
  - docker
  - dropbox
  - fantastical
  - firefox
  - google-chrome
  - handbrake
  - install-disk-creator
  - licecap
  - limechat
  - logmein-hamachi
  - mathpix-snipping-tool
  - sequel-pro
  - sourcetree
  - sublime-text
  - transmit
  - typora
  - vagrant
  - vlc
  - whatsapp
  - yacreader
homebrew_cask_uninstalled_apps:
  - chromedriver
  - macvim
  - skitch
  - slack
homebrew_upgrade_all_packages: no

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 425264550, name: "Blackmagic Disk Speed Test (3.0)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: 
  - name: hirak/prestissimo
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: 
  - name: yarn
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: 
  - name: mkdocs
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
