---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/tedbundyjr/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Developments/dotfiles

dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .ssh/config
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - limechat
  - macvim
  - sequel-pro
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 412759995, name: "Guidance (2.0.8)" }
  - { id: 639764244, name: "Xee³ (3.5.3)" }
  - { id: 408981434, name: "iMovie (10.1.10)" }
  - { id: 409183694, name: "Keynote (8.3)" }
  - { id: 411673888, name: "EasyFind (4.9.3)" }
  - { id: 1185488696, name: "Money (5.6.7)" }
  - { id: 585829637, name: "Todoist (7.1.2)" }
  - { id: 409201541, name: "Pages (7.3)" }
  - { id: 425264550, name: "Blackmagic Disk Speed Test (3.2)" }
  - { id: 411622604, name: "Quran Majeed (3.5)" }
  - { id: 1293083751, name: "GSE SMART IPTV (3.7)" }
  - { id: 411643860, name: "DaisyDisk (4.6.5)" }
  - { id: 409203825, name: "Numbers (5.3)" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
